# Generated by Django 5.2.1 on 2025-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topper',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
