# Generated by Django 5.2.1 on 2025-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Emails', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
