# Generated by Django 5.2.1 on 2025-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_login_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
