# Generated by Django 5.2.1 on 2025-05-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Emails',
            new_name='email',
        ),
    ]
