# Generated by Django 5.2.1 on 2025-05-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='no',
            field=models.IntegerField(default=9022701981),
            preserve_default=False,
        ),
    ]
