# Generated by Django 5.2.1 on 2025-05-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Emails',
            new_name='email',
        ),
    ]
