# Generated by Django 5.2.1 on 2025-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('select_course_type', models.CharField(choices=[('MHT-CET', 'MHT-CET'), ('NEET', 'Neet')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Toppers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topper_name', models.CharField(max_length=100)),
                ('topper_course', models.CharField(choices=[('MHT-CET', 'MHT-CET'), ('NEET', 'Neet')], max_length=100)),
            ],
        ),
    ]
