# Generated by Django 5.2.1 on 2025-05-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='toppers',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
