# Generated by Django 5.2.1 on 2025-05-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
    ]
