# Generated by Django 5.2.1 on 2025-05-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newsettleer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsettleer',
            old_name='Emails',
            new_name='email',
        ),
    ]
